### ISSUE TITLE
Deselecting members does not work

### ISSUE THREAD

**Issue by devaccount89** [liprec/powerbi-hierarchySlicer#37]
If you have  multi selected turned on and  have selected multiple members, the deselection of a member does not work. 
-------------------------
Example 
o Member one ( selected)
o Member two (selected)
data filtered
Try to deselect  Member two. -> not working. 

You need to fully clear the slicer ( button top right) to be able to change / reapply the selection.

**Comment by liprec** [comment]
This is unfortunately the case when the current selection is saved to the report using old logic.
Is it possible to save the report with first clearing the current selection and then reapply the selection?
That should solve the problem.

-JP

**Comment by devaccount89** [comment]
No, this does not solve the problem. And it only appears to be the case on the lowest element. If i select two on the lowest element and then try to change the selection it is not working. However only selecting one and deselecting one is working. 

Thanks.

**Comment by liprec** [comment]
Is it possible to share an example PBIX with me?

**Comment by devaccount89** [comment]
Hi JP, 

please find attached an example file. 
Deselecting of member 6 / 8 is not working.

Thanks

Dev89
[IssuePBIX.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/2302855/IssuePBIX.zip)

**Comment by liprec** [comment]
Thanks for the sample and indeed this is not how it should be working.
But the good news is that it is already fixed in the upcoming version (v1.3) that will be available next week.

**Comment by devaccount89** [comment]
Hi JP, 

great to hear and amazing support from your end!
Keep up the good work!!
Thanks, 

Dev89

**Comment by devaccount89** [comment]
Hi Jan, 
is the v1.3 available yet? 👍  Do not see it here on git. 

Thanks. 

Dev89

**Comment by liprec** [comment]
I will push the new code when the new version is available for everyone.
I am expecting that it is being released this week.

**Comment by liprec** [comment]
Fixed with version v1.3

**Comment by devaccount89** [comment]
Thanks Jan! 
Amazing and many kudos for  the good work! 
Keep on going 🥇 

Thanks. 
Dev89
